### PR TITLE
Fix compiling

### PR DESCRIPTION
**Pull request by tobid7**

### CODE REVIEW

**Comment by Byebyesky** [comment]
Hello!
Thank you so much for your pull request!
Are you able to provide a bit more information for this?

Because for me both versions compile no problem, so I'm not exactly sure what the change is for.
Which version of libctru are you using?
Please make sure it's the newest version v2.0.1 when compiling luma3ds

**Comment by tobid7** [comment]
Hello, I've used the newest version i think... Just installed libctru some days ago my manjaro(to many problrms with windows.)

After compiling ill cott an error in this line.

**Comment by tobid7** [comment]
I've got this error here...

error

**Comment by Byebyesky** [comment]
Hi! Thanks for getting back to me!
This is caused by an older libctru version that is distributed with dkp-pacman.
[This commit](https://github.com/devkitPro/libctru/commit/4fdc40228a8eba6f62b5421aa52b4c980398d8ea) adds this function.
Clone the newest [libctru](https://github.com/devkitPro/libctru), run make.
Since you already have devkitpro installed, you can just delete /opt/devkitpro/libctru and mv libctru /opt/devkitpro/
After that it should compile without a problem.

**Comment by tobid7** [comment]
Ah ok.

**Comment by tobid7** [comment]
Just a Question:

Is that normal that I get an empty 3ds view window??

**Comment by Byebyesky** [comment]
Can you describe your problem more closely?

This software is very buggy and isn't ready for actual use in streaming. It was more a toy project to see what is possible and whether I can integrate streaming into luma3ds directly.
So the connection sometimes just randomly breaks.

If you mean you can't connect to the 3DS using the python script, did you change the IP in the **streaming.py** script to your 3DS'?
Make sure to start the streaming on the 3DS side first and then open the python script on your PC.

**Pull request closed without merging**
